name: TruffleHog Scan

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Run TruffleHog
        run: trufflehog git file://$(pwd) --json > trufflehog-results.json

      - name: Convert TruffleHog results to SARIF
        run: |
          pip install sarif-tools
          cat trufflehog-results.json | trufflehog2sarif > trufflehog-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trufflehog-results.sarif